//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baltoppen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MovieId { get; set; }
        public string MovieTitle { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Thumbnail { get; set; }
    }
}
