//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baltoppen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaltoppenEntities1 : DbContext
    {
        public BaltoppenEntities1()
            : base("name=BaltoppenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<ReservedSeats> ReservedSeats { get; set; }
        public virtual DbSet<Screenings> Screenings { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<SoldProducts> SoldProducts { get; set; }
        public virtual DbSet<Theaters> Theaters { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
