//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baltoppen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public int SeatId { get; set; }
        public int SeatRow { get; set; }
        public int SeatNumber { get; set; }
        public int FkTheaterId { get; set; }
    }
}
