//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baltoppen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldProducts
    {
        public int ProductId { get; set; }
        public string ProductType { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomText { get; set; }
        public bool Delivered { get; set; }
    }
}
